### ISSUE TITLE
Error in uploading : "We are unable to create an authentication session"

### ISSUE THREAD

**Issue by yasheshc** [bitrise-steplib/steps-deploy-to-itunesconnect-application-loader#22]
I'm having a problem with a specific app only. For another app, it works fine.

Here the log of the error

$ xcrun "altool" "--upload-app" "-f" "/Users/vagrant/deploy/Staging-Release.ipa" "-u" "MYEMAIL\n" "-p" "[REDACTED]"
2020-04-26 14:58:38.151 altool[5452:21892] *** Error: Errors uploading '/Users/vagrant/deploy/Staging-Release.ipa': (
    "Error Domain=ITunesSoftwareServiceErrorDomain Code=-22014 \"We are unable to create an authentication session.\" UserInfo={NSLocalizedDescription=We are unable to create an authentication session., NSLocalizedFailureReason=Unable to validate your application.}"
)

**Comment by saransh-malik** [comment]
Hi, how did you solve this out? Facing the same issue. @yasheshc

**Comment by GForceWeb** [comment]
I'm getting this error on a few of our apps as well.

@yasheshc did you figure it out? Or @saransh-malik did you work anything out?

**Comment by saransh-malik** [comment]
Make sure in teams tab, the session based auth is working well, for me it was since my apple account had 2 factor authentication I had to from time to time update this. The other solution is to start using Apple Developer Portal API method to connect your apple account in Bitrise

**Comment by bitce** [comment]
To everyone experiencing this issue, also make sure you have an Application Specific Password added to the step!

**Comment by GForceWeb** [comment]
@saransh-malik - I was specifically using this step instead of the other Deploy to iTunes Connect step as this step did not require the session based auth in Bitrise. This step was (and still is for some apps) working just fine with just the Apple Username, Password and AppSpecificPw.

I still haven't been able to verify the difference between my apps/accounts that are submitting successfully with this step and the ones that are failing with this error. The full workflow is identical and I've verified the credentials are correct.
